tap "azure/functions"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
tap "zkokaja/brewlet"
brew "antigen"
brew "azure-cli"
brew "docker", link: false
brew "dockutil"
brew "exa"
brew "exiftool"
brew "ffmpeg"
brew "git"
brew "gnupg"
brew "handbrake", link: false
brew "jq"
brew "mas"
brew "mkvtoolnix"
brew "mp4v2"
brew "pyenv"
brew "rdfind"
brew "streamlink"
brew "tree"
brew "wireguard-tools"
brew "yarn"
brew "youtube-dl"
brew "z"
brew "azure/functions/azure-functions-core-tools@2"
brew "mongodb/brew/mongodb-community"
cask "1password"
cask "1password-cli"
cask "aerial"
cask "affinity-designer-beta"
cask "affinity-photo-beta"
cask "alfred"
cask "arq"
cask "balenaetcher"
cask "brewlet"
cask "discord"
cask "docker"
cask "dupeguru"
cask "figma"
cask "firefox"
cask "font-fira-code"
cask "franz"
cask "github-beta"
cask "handbrake"
cask "iina"
cask "intel-power-gadget"
cask "iterm2-beta"
cask "logitech-options"
cask "makemkv"
cask "microsoft-edge-dev"
cask "microsoft-office"
cask "microsoft-teams"
cask "mongodb-compass-community"
cask "ngrok"
cask "notion"
cask "obs"
cask "philips-hue-sync"
cask "plex"
cask "pritunl"
cask "qlab"
cask "safari-technology-preview"
cask "transmit"
cask "visual-studio-code-insiders"
cask "vlc"
cask "vmware-fusion"
cask "webex-meetings"
mas "CARROT Weather", id: 993487541
mas "Dark Mode for Safari", id: 1397180934
mas "Developer", id: 640199958
mas "Final Cut Pro", id: 424389933
mas "Honey", id: 1472777122
mas "Keynote", id: 409183694
mas "Mactracker", id: 430255202
mas "Messenger", id: 1480068668
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PiPifier", id: 1160374471
