tap "azure/functions"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-drivers"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
brew "antigen"
brew "azure-cli"
brew "azure/functions/azure-functions-core-tools@2"
brew "docker"
brew "dockutil"
brew "exa"
brew "git"
brew "gnupg"
brew "jq"
brew "mas"
brew "mongodb/brew/mongodb-community"
brew "rdfind"
brew "tree"
brew "yarn"
brew "z"
cask "1password-cli"
cask "1password"
cask "aerial"
cask "affinity-designer-beta"
cask "affinity-photo-beta"
cask "alfred"
cask "arq"
cask "docker"
cask "dupeguru"
cask "figma"
cask "firefox"
cask "franz"
cask "github-beta"
cask "google-chrome"
cask "gswitch"
cask "iina"
cask "intel-power-gadget"
cask "iterm2-beta"
cask "logitech-options"
cask "microsoft-edge-dev"
cask "microsoft-office"
cask "mongodb-compass-community"
cask "ngrok"
cask "notion"
cask "obs"
cask "philips-hue-sync"
cask "plex"
cask "private-internet-access"
cask "qlab"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "safari-technology-preview"
cask "setapp"
cask "soundsource"
cask "tower"
cask "transmit"
cask "visual-studio-code-insiders"
cask "vmware-fusion"
cask "webex-meetings"
cask "webpquicklook"
mas "CARROT Weather", id: 993487541
mas "Final Cut Pro", id: 424389933
mas "Keynote", id: 409183694
mas "Mactracker", id: 430255202
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PiPifier", id: 1160374471
mas "Twitter", id: 1482454543
mas "Spark", id: 1176895641