#!/bin/bash

sudo -v

dockutil --no-restart --remove all
dockutil --no-restart --add "/System/Applications/App Store.app"
dockutil --no-restart --add "/Applications/Safari Technology Preview.app"
dockutil --no-restart --add "/Applications/Microsoft Edge Dev.app"
dockutil --no-restart --add "/System/Applications/Music.app"
dockutil --no-restart --add "/Applications/Plex.app"
dockutil --no-restart --add "/System/Applications/Messages.app"
dockutil --no-restart --add "/Applications/Franz.app"
dockutil --no-restart --add "/Applications/Spark.app"
dockutil --no-restart --add "/Applications/Notion.app"
dockutil --no-restart --add "/Applications/Figma.app"
dockutil --no-restart --add "/Applications/iTerm.app"
dockutil --no-restart --add "/Applications/Transmit.app"
dockutil --no-restart --add "/Applications/GitHub Desktop.app"
dockutil --no-restart --add "/Applications/Visual Studio Code - Insiders.app"
dockutil --no-restart --add "/System/Applications/System Preferences.app"
dockutil --no-restart --add "~/Downloads"

killall Dock