#!/bin/sh
# Install all dotfiles into the home directory

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)

[ $(uname -s) = "Darwin" ] && export MACOS=1 && export UNIX=1
[ $(uname -s) = "Linux" ] && export LINUX=1 && export UNIX=1
uname -s | grep -q "_NT-" && export WINDOWS=1

if [ $UNIX ]
then
  ln -sfv $DOTFILESDIR/Brewfile ~/.Brewfile
  ln -sfv $DOTFILESDIR/Brewfile.lock.json ~/.Brewfile.lock.json
  ln -sfv $DOTFILESDIR/gitconfig ~/.gitconfig
  ln -sfv $DOTFILESDIR/gitignore ~/.gitignore
  ln -sfv $DOTFILESDIR/zshrc.sh ~/.zshrc
  ln -sfv $DOTFILESDIR/starship.toml ~/.config/starship.toml
  rm -rf ~/.gnupg
  ln -sfv $DOTFILESDIR/gnupg ~/.gnupg
  rm -rf ~/.ssh
  ln -sfv $DOTFILESDIR/ssh ~/.ssh
  mkdir ~/Developer
  ln -sfv $DOTFILESDIR/finicky.js ~/.finicky.js
  touch ~/.hushlogin
fi
